import re

with open(r"C:\Users\Z\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\earshot-1.2.2\src\filters.rs", encoding="utf-8") as f:
    filters_code = f.read()

with open(r"C:\Users\Z\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\earshot-1.2.2\src\fft\tables.rs", encoding="utf-8") as f:
    tables_code = f.read()

# Extract HANN_WINDOW
hann_match = re.search(r"pub static HANN_WINDOW: \[f32; 768\] = \[(.*?)\];", filters_code, re.DOTALL)
hann_vals = [x.strip() for x in hann_match.group(1).split(",") if x.strip()]

# Extract MEL_COEFFS
mel_lines = re.findall(r"\((\d+),\s*&\[(.*?)\]\)", filters_code)

# Extract SINE
sine_match = re.search(r"pub\(crate\) const SINE: &\[f32\] = &\[(.*?)\];", tables_code, re.DOTALL)
sine_vals = [x.strip() for x in sine_match.group(1).split(",") if x.strip()]

# Extract BITREV[9] (512 values)
bitrev_match = re.search(r"pub\(crate\) const BITREV: &\[&\[u16\]\] = &\[(.*?)\];", tables_code, re.DOTALL)
bitrev_blocks = re.findall(r"&\[(.*?)\]", bitrev_match.group(1), re.DOTALL)
bitrev_9_vals = [x.strip() for x in bitrev_blocks[9].split(",") if x.strip()]

out = []
out.append('// transcribe-vad.cpp - native Earshot minGRU voice activity detection.')
out.append('// Clean-room C++23 kernel with 100% bit-exact parity to Earshot v1.2.2.')
out.append('#include "transcribe-vad.h"')
out.append('#include "earshot-weights.inl"')
out.append('#include "transcribe-session.h"')
out.append('#include "transcribe-log.h"')
out.append('')
out.append('#include <algorithm>')
out.append('#include <cmath>')
out.append('#include <cstring>')
out.append('#include <new>')
out.append('')
out.append('namespace transcribe {')
out.append('namespace {')
out.append('')
out.append('// ---------------------------------------------------------------------------')
out.append('// Hann Window (768 samples, periodic)')
out.append('// ---------------------------------------------------------------------------')
out.append('alignas(32) constexpr float HANN_WINDOW[768] = {')
for i in range(0, len(hann_vals), 8):
    chunk = hann_vals[i:i+8]
    out.append('    ' + ', '.join(f'{v}f' for v in chunk) + ',')
out.append('};')
out.append('')
out.append('// ---------------------------------------------------------------------------')
out.append('// Mel Filterbank (40 bands)')
out.append('// ---------------------------------------------------------------------------')
out.append('struct MelBand {')
out.append('    uint16_t start;')
out.append('    uint16_t count;')
out.append('    const float * coeffs;')
out.append('};')
out.append('')
for idx, (start, coeffs_str) in enumerate(mel_lines):
    vals = [x.strip() for x in coeffs_str.split(',') if x.strip()]
    out.append(f'constexpr float MEL_COEFFS_{idx}[{len(vals)}] = {{ ' + ', '.join(f'{v}f' for v in vals) + ' };')

out.append('')
out.append('constexpr MelBand MEL_FILTERS[40] = {')
for idx, (start, coeffs_str) in enumerate(mel_lines):
    vals = [x.strip() for x in coeffs_str.split(',') if x.strip()]
    out.append(f'    {{ {start}, {len(vals)}, MEL_COEFFS_{idx} }},')
out.append('};')
out.append('')
out.append('// ---------------------------------------------------------------------------')
out.append('// FFT Tables (SINE and BITREV for 512 complex / 1024 real points)')
out.append('// ---------------------------------------------------------------------------')
out.append('constexpr float SINE_TABLE[255] = {')
for i in range(0, len(sine_vals), 6):
    chunk = sine_vals[i:i+6]
    out.append('    ' + ', '.join(f'{v}f' for v in chunk) + ',')
out.append('};')
out.append('')
out.append('constexpr uint16_t BITREV_512[512] = {')
for i in range(0, len(bitrev_9_vals), 16):
    chunk = bitrev_9_vals[i:i+16]
    out.append('    ' + ', '.join(chunk) + ',')
out.append('};')
out.append('')
out.append('// ---------------------------------------------------------------------------')
out.append('// Complex Arithmetic and 1024-Point Real FFT')
out.append('// ---------------------------------------------------------------------------')
out.append('struct Complex32 {')
out.append('    float re = 0.0f;')
out.append('    float im = 0.0f;')
out.append('')
out.append('    constexpr Complex32() = default;')
out.append('    constexpr Complex32(float r, float i) : re(r), im(i) {}')
out.append('')
out.append('    [[nodiscard]] constexpr float norm_sqr() const noexcept {')
out.append('        return re * re + im * im;')
out.append('    }')
out.append('')
out.append('    constexpr Complex32 operator+(const Complex32 & rhs) const noexcept {')
out.append('        return {re + rhs.re, im + rhs.im};')
out.append('    }')
out.append('    constexpr Complex32 operator-(const Complex32 & rhs) const noexcept {')
out.append('        return {re - rhs.re, im - rhs.im};')
out.append('    }')
out.append('    constexpr Complex32 operator*(const Complex32 & rhs) const noexcept {')
out.append('        return {re * rhs.re - im * rhs.im, re * rhs.im + im * rhs.re};')
out.append('    }')
out.append('    constexpr Complex32 operator*(float rhs) const noexcept {')
out.append('        return {re * rhs, im * rhs};')
out.append('    }')
out.append('};')
out.append('')
out.append('template <size_t N>')
out.append('struct CFft {')
out.append('    static void compute_butterflies(Complex32 * x) noexcept {')
out.append('        constexpr size_t m = N / 2;')
out.append('        constexpr size_t u = m / 2;')
out.append('        constexpr size_t table_len = 255;')
out.append('        constexpr size_t table_stride = (table_len + 1) * 4 / N;')
out.append('')
out.append('        CFft<m>::compute_butterflies(x);')
out.append('        CFft<m>::compute_butterflies(x + m);')
out.append('')
out.append('        // k = 0')
out.append('        Complex32 x_0 = x[0];')
out.append('        Complex32 x_m = x[m];')
out.append('        x[0] = x_0 + x_m;')
out.append('        x[m] = x_0 - x_m;')
out.append('')
out.append('        for (size_t k = 1; k < u; ++k) {')
out.append('            size_t s = k * table_stride;')
out.append('            float re = SINE_TABLE[table_len - s] * -1.0f;')
out.append('            float im = SINE_TABLE[s - 1];')
out.append('            Complex32 twiddle{re, im};')
out.append('            Complex32 x_k = x[k];')
out.append('            Complex32 x_km = x[k + m];')
out.append('            Complex32 y = twiddle * x_km;')
out.append('            x[k] = x_k + y;')
out.append('            x[k + m] = x_k - y;')
out.append('        }')
out.append('')
out.append('        Complex32 x_u = x[u];')
out.append('        Complex32 x_um = x[u + m];')
out.append('        Complex32 y = x_um * Complex32{0.0f, -1.0f};')
out.append('        x[u] = x_u + y;')
out.append('        x[u + m] = x_u - y;')
out.append('')
out.append('        for (size_t k = u + 1; k < m; ++k) {')
out.append('            size_t s = (k - u) * table_stride;')
out.append('            float re = SINE_TABLE[s - 1];')
out.append('            float im = SINE_TABLE[table_len - s];')
out.append('            Complex32 twiddle{re, im};')
out.append('            Complex32 x_k = x[k];')
out.append('            Complex32 x_km = x[k + m];')
out.append('            Complex32 y = twiddle * x_km;')
out.append('            x[k] = x_k + y;')
out.append('            x[k + m] = x_k - y;')
out.append('        }')
out.append('    }')
out.append('};')
out.append('')
out.append('template <>')
out.append('struct CFft<1> {')
out.append('    static void compute_butterflies(Complex32 *) noexcept {}')
out.append('};')
out.append('')
out.append('template <>')
out.append('struct CFft<2> {')
out.append('    static void compute_butterflies(Complex32 * x) noexcept {')
out.append('        Complex32 x_0 = x[0];')
out.append('        Complex32 x_1 = x[1];')
out.append('        x[0] = x_0 + x_1;')
out.append('        x[1] = x_0 - x_1;')
out.append('    }')
out.append('};')
out.append('')
out.append('void rfft_1024(float * buffer_1026) noexcept {')
out.append('    auto * comp = reinterpret_cast<Complex32 *>(buffer_1026);')
out.append('    for (size_t i = 0; i < 512; ++i) {')
out.append('        size_t j = BITREV_512[i];')
out.append('        if (i < j) {')
out.append('            std::swap(comp[i], comp[j]);')
out.append('        }')
out.append('    }')
out.append('    CFft<512>::compute_butterflies(comp);')
out.append('')
out.append('    constexpr size_t m = 512;')
out.append('    constexpr size_t table_len = 255;')
out.append('    constexpr size_t table_stride = 1;')
out.append('')
out.append('    Complex32 x0 = comp[0];')
out.append('    comp[0] = Complex32{x0.re + x0.im, x0.re - x0.im};')
out.append('')
out.append('    constexpr size_t u = 256;')
out.append('    for (size_t k = 1; k < u; ++k) {')
out.append('        size_t s = k * table_stride;')
out.append('        float twiddle_re = SINE_TABLE[table_len - s] * -1.0f;')
out.append('        float twiddle_im = SINE_TABLE[s - 1];')
out.append('')
out.append('        Complex32 x_k = comp[k];')
out.append('        Complex32 x_nk = comp[m - k];')
out.append('        Complex32 sum{(x_k.re + x_nk.re) * 0.5f, (x_k.im + x_nk.im) * 0.5f};')
out.append('        Complex32 diff{(x_k.re - x_nk.re) * 0.5f, (x_k.im - x_nk.im) * 0.5f};')
out.append('')
out.append('        comp[k] = Complex32{')
out.append('            sum.re + twiddle_re * sum.im + twiddle_im * diff.re,')
out.append('            diff.im + twiddle_im * sum.im - twiddle_re * diff.re')
out.append('        };')
out.append('        comp[m - k] = Complex32{')
out.append('            sum.re - twiddle_re * sum.im - twiddle_im * diff.re,')
out.append('            -diff.im + twiddle_im * sum.im - twiddle_re * diff.re')
out.append('        };')
out.append('    }')
out.append('')
out.append('    Complex32 xu = comp[u];')
out.append('    comp[u] = Complex32{xu.re, -xu.im};')
out.append('')
out.append('    comp[512].re = comp[0].im;')
out.append('    comp[512].im = 0.0f;')
out.append('    comp[0].im = 0.0f;')
out.append('}')
out.append('')
out.append('// ---------------------------------------------------------------------------')
out.append('// Model Weights Pointers from embedded static binary')
out.append('// ---------------------------------------------------------------------------')
out.append('inline const float * weight_f32(size_t offset) noexcept {')
out.append('    return reinterpret_cast<const float *>(EARSHOT_WEIGHTS_BIN) + offset;')
out.append('}')
out.append('inline const int16_t * weight_i16(size_t offset) noexcept {')
out.append('    return reinterpret_cast<const int16_t *>(EARSHOT_WEIGHTS_BIN) + (offset * 2);')
out.append('}')
out.append('')
out.append('inline const float * NORM_WEIGHT() noexcept { return weight_f32(0); }')
out.append('inline const float * LAYER1_KERNEL() noexcept { return weight_f32(40); }')
out.append('inline const float * LAYER1_WEIGHT() noexcept { return weight_f32(49); }')
out.append('inline const float * LAYER1_BIAS() noexcept { return weight_f32(65); }')
out.append('inline const float * LAYER2_KERNEL() noexcept { return weight_f32(81); }')
out.append('inline const float * LAYER2_WEIGHT() noexcept { return weight_f32(129); }')
out.append('inline const float * LAYER2_BIAS() noexcept { return weight_f32(385); }')
out.append('inline const float * LAYER3_KERNEL() noexcept { return weight_f32(401); }')
out.append('inline const float * LAYER3_WEIGHT() noexcept { return weight_f32(449); }')
out.append('inline const int16_t * RNN1_WEIGHT() noexcept { return weight_i16(705); }')
out.append('inline const int16_t * RNN2_WEIGHT() noexcept { return weight_i16(5825); }')
out.append('inline const int16_t * OUTPUT_WEIGHT() noexcept { return weight_i16(9921); }')
out.append('')
out.append('void input_layer1(const float * features, float * output) noexcept {')
out.append('    constexpr size_t NUM_FRAMES = 3;')
out.append('    constexpr size_t NUM_FEATURES = 40;')
out.append('    constexpr size_t KERNEL_SIZE = 3;')
out.append('    constexpr size_t DEPTHWISE_NUM_FEATURES = (NUM_FEATURES - KERNEL_SIZE) + 1; // 38')
out.append('    constexpr size_t OUT_CHANNELS = 16;')
out.append('    constexpr size_t POOL_KERNEL_SIZE = 3;')
out.append('    constexpr size_t POOL_STRIDE = 2;')
out.append('    constexpr size_t POOLED_COLS = (DEPTHWISE_NUM_FEATURES - POOL_KERNEL_SIZE) / POOL_STRIDE + 1; // 18')
out.append('')
out.append('    std::memset(output, 0, OUT_CHANNELS * POOLED_COLS * sizeof(float));')
out.append('    float row[DEPTHWISE_NUM_FEATURES] = {0};')
out.append('    const float * l1_kernel = LAYER1_KERNEL();')
out.append('    const float * l1_weight = LAYER1_WEIGHT();')
out.append('    const float * l1_bias   = LAYER1_BIAS();')
out.append('')
out.append('    for (size_t ox = 0; ox < DEPTHWISE_NUM_FEATURES; ++ox) {')
out.append('        float sum = 0.0f;')
out.append('        for (size_t kh = 0; kh < KERNEL_SIZE; ++kh) {')
out.append('            for (size_t kw = 0; kw < KERNEL_SIZE; ++kw) {')
out.append('                size_t input_idx = kh * NUM_FEATURES + (ox + kw);')
out.append('                sum += features[input_idx] * l1_kernel[kh * KERNEL_SIZE + kw];')
out.append('            }')
out.append('        }')
out.append('        row[ox] = sum;')
out.append('    }')
out.append('')
out.append('    for (size_t c = 0; c < OUT_CHANNELS; ++c) {')
out.append('        float new_row[DEPTHWISE_NUM_FEATURES];')
out.append('        float wc = l1_weight[c];')
out.append('        float bc = l1_bias[c];')
out.append('        for (size_t ox = 0; ox < DEPTHWISE_NUM_FEATURES; ++ox) {')
out.append('            new_row[ox] = row[ox] * wc + bc;')
out.append('        }')
out.append('')
out.append('        size_t out_row_offs = POOLED_COLS * c;')
out.append('        for (size_t q = 0; q < POOLED_COLS; ++q) {')
out.append('            float max_val = output[out_row_offs + q]; // acts as ReLU since initialized to 0')
out.append('            for (size_t x = 0; x < POOL_KERNEL_SIZE; ++x) {')
out.append('                max_val = std::max(max_val, new_row[q * POOL_STRIDE + x]);')
out.append('            }')
out.append('            output[out_row_offs + q] = max_val;')
out.append('        }')
out.append('    }')
out.append('}')
out.append('')
out.append('void input_layer2(const float * features, float * output) noexcept {')
out.append('    constexpr size_t IN_FEATURES = 18;')
out.append('    constexpr size_t OUT_FEATURES = 9;')
out.append('    constexpr size_t HORIZONTAL_KERNEL_SIZE = 3;')
out.append('    constexpr size_t STRIDE = 2;')
out.append('    constexpr size_t CHANNELS = 16;')
out.append('    const float * l2_kernel = LAYER2_KERNEL();')
out.append('    const float * l2_weight = LAYER2_WEIGHT();')
out.append('    const float * l2_bias   = LAYER2_BIAS();')
out.append('')
out.append('    for (size_t ox = 0; ox < OUT_FEATURES; ++ox) {')
out.append('        float dw[CHANNELS] = {0};')
out.append('        for (size_t c = 0; c < CHANNELS; ++c) {')
out.append('            float sum = 0.0f;')
out.append('            for (size_t kw = 0; kw < HORIZONTAL_KERNEL_SIZE; ++kw) {')
out.append('                intptr_t ix = static_cast<intptr_t>(ox * STRIDE + kw) - 1;')
out.append('                if (ix >= 0 && ix < static_cast<intptr_t>(IN_FEATURES)) {')
out.append('                    sum += features[c * IN_FEATURES + static_cast<size_t>(ix)] * l2_kernel[c * HORIZONTAL_KERNEL_SIZE + kw];')
out.append('                }')
out.append('            }')
out.append('            dw[c] = sum;')
out.append('        }')
out.append('        for (size_t oc = 0; oc < CHANNELS; ++oc) {')
out.append('            float ic = 0.0f;')
out.append('            for (size_t c = 0; c < CHANNELS; ++c) {')
out.append('                ic += dw[c] * l2_weight[oc * CHANNELS + c];')
out.append('            }')
out.append('            output[oc * OUT_FEATURES + ox] = std::max(0.0f, ic + l2_bias[oc]);')
out.append('        }')
out.append('    }')
out.append('}')
out.append('')
out.append('void input_layer3(const float * features, int16_t * output) noexcept {')
out.append('    constexpr size_t IN_FEATURES = 9;')
out.append('    constexpr size_t OUT_FEATURES = 5;')
out.append('    constexpr size_t HORIZONTAL_KERNEL_SIZE = 3;')
out.append('    constexpr size_t STRIDE = 2;')
out.append('    constexpr size_t CHANNELS = 16;')
out.append('    const float * l3_kernel = LAYER3_KERNEL();')
out.append('    const float * l3_weight = LAYER3_WEIGHT();')
out.append('')
out.append('    for (size_t ox = 0; ox < OUT_FEATURES; ++ox) {')
out.append('        float dw[CHANNELS] = {0};')
out.append('        for (size_t c = 0; c < CHANNELS; ++c) {')
out.append('            float sum = 0.0f;')
out.append('            for (size_t kw = 0; kw < HORIZONTAL_KERNEL_SIZE; ++kw) {')
out.append('                intptr_t ix = static_cast<intptr_t>(ox * STRIDE + kw) - 1;')
out.append('                if (ix >= 0 && ix < static_cast<intptr_t>(IN_FEATURES)) {')
out.append('                    sum += features[c * IN_FEATURES + static_cast<size_t>(ix)] * l3_kernel[c * HORIZONTAL_KERNEL_SIZE + kw];')
out.append('                }')
out.append('            }')
out.append('            dw[c] = sum;')
out.append('        }')
out.append('        for (size_t oc = 0; oc < CHANNELS; ++oc) {')
out.append('            float ic = 0.0f;')
out.append('            for (size_t c = 0; c < CHANNELS; ++c) {')
out.append('                ic += dw[c] * l3_weight[oc * CHANNELS + c];')
out.append('            }')
out.append('            float scaled = std::round(ic * 32768.0f);')
out.append('            scaled = std::clamp(scaled, -32768.0f, 32767.0f);')
out.append('            output[ox * CHANNELS + oc] = static_cast<int16_t>(scaled);')
out.append('        }')
out.append('    }')
out.append('}')
out.append('')
out.append('template <size_t IN_DIM>')
out.append('void mingru(const int16_t * features, int16_t * h, const int16_t * weight, int32_t * temp) noexcept {')
out.append('    for (size_t d = 0; d < 128; ++d) {')
out.append('        int32_t o = 0;')
out.append('        size_t ri = d * IN_DIM;')
out.append('        for (size_t f = 0; f < IN_DIM; ++f) {')
out.append('            o += static_cast<int32_t>(features[f]) * static_cast<int32_t>(weight[ri + f]);')
out.append('        }')
out.append('        temp[d] = o;')
out.append('    }')
out.append('')
out.append('    for (size_t i = 0; i < 64; ++i) {')
out.append('        int64_t g = std::clamp<int64_t>(static_cast<int64_t>(temp[64 + i]) << 2, 0, 16777215);')
out.append('        int64_t y = (16777215 - g) * (static_cast<int64_t>(h[i]) << 9) + g * static_cast<int64_t>(temp[i]);')
out.append('        h[i] = static_cast<int16_t>(std::clamp<int64_t>(y >> 33, -32768, 32767));')
out.append('    }')
out.append('}')
out.append('')
out.append('inline float sigmoid(float x) noexcept {')
out.append('    return 1.0f / (1.0f + std::exp(-x));')
out.append('}')
out.append('')
out.append('float output_layer(const int16_t * state) noexcept {')
out.append('    int32_t out = 0;')
out.append('    const int16_t * output_weight = OUTPUT_WEIGHT();')
out.append('    for (size_t f = 0; f < 128; ++f) {')
out.append('        out += static_cast<int32_t>(state[f]) * static_cast<int32_t>(output_weight[f]);')
out.append('    }')
out.append('    return sigmoid(static_cast<float>(out) / 16777216.0f);')
out.append('}')
out.append('')
out.append('} // namespace')
out.append('')
out.append('struct VoiceActivityDetector::Impl {')
out.append('    float prev_signal = 0.0f;')
out.append('    alignas(32) float sample_ring_buffer[768] = {0};')
out.append('    alignas(32) float features[40 * 3] = {0};')
out.append('    alignas(32) float buffer[1026] = {0};')
out.append('    int16_t rnn_state[128] = {0};')
out.append('')
out.append('    void reset() noexcept {')
out.append('        prev_signal = 0.0f;')
out.append('        std::memset(sample_ring_buffer, 0, sizeof(sample_ring_buffer));')
out.append('        std::memset(features, 0, sizeof(features));')
out.append('        std::memset(buffer, 0, sizeof(buffer));')
out.append('        std::memset(rnn_state, 0, sizeof(rnn_state));')
out.append('    }')
out.append('')
out.append('    float predict_f32(std::span<const float, 256> frame) noexcept {')
out.append('        constexpr float SCALE = 32768.0f;')
out.append('        constexpr float PRE_EMPHASIS_COEFF = 0.97f;')
out.append('        constexpr float POWER_FAC = 1.0f / (32768.0f * 32768.0f);')
out.append('')
out.append('        std::memmove(sample_ring_buffer, sample_ring_buffer + 256, 512 * sizeof(float));')
out.append('        for (size_t i = 0; i < 256; ++i) {')
out.append('            float s = frame[i] * SCALE;')
out.append('            sample_ring_buffer[512 + i] = s - PRE_EMPHASIS_COEFF * prev_signal;')
out.append('            prev_signal = s;')
out.append('        }')
out.append('')
out.append('        for (size_t i = 0; i < 768; ++i) {')
out.append('            buffer[i] = sample_ring_buffer[i] * HANN_WINDOW[i];')
out.append('        }')
out.append('        std::memset(buffer + 768, 0, (256 + 2) * sizeof(float));')
out.append('')
out.append('        rfft_1024(buffer);')
out.append('')
out.append('        auto * comp = reinterpret_cast<Complex32 *>(buffer);')
out.append('        for (size_t i = 0; i < 513; ++i) {')
out.append('            buffer[i] = comp[i].norm_sqr() * POWER_FAC;')
out.append('        }')
out.append('')
out.append('        std::memmove(features, features + 40, 40 * 2 * sizeof(float));')
out.append('        float * cur_frame_features = features + 40 * 2;')
out.append('')
out.append('        for (size_t i = 0; i < 40; ++i) {')
out.append('            float per_band_value = 0.0f;')
out.append('            const auto & mel = MEL_FILTERS[i];')
out.append('            for (size_t j = 0; j < mel.count; ++j) {')
out.append('                per_band_value += buffer[mel.start + j] * mel.coeffs[j];')
out.append('            }')
out.append('            cur_frame_features[i] = std::log(per_band_value + 1e-20f);')
out.append('        }')
out.append('')
out.append('        float sum_sq = 0.0f;')
out.append('        for (size_t i = 0; i < 40; ++i) {')
out.append('            sum_sq += cur_frame_features[i] * cur_frame_features[i];')
out.append('        }')
out.append('        float i_rms = 1.0f / std::sqrt(sum_sq / 40.0f);')
out.append('        const float * norm_w = NORM_WEIGHT();')
out.append('        for (size_t i = 0; i < 40; ++i) {')
out.append('            cur_frame_features[i] = norm_w[i] * cur_frame_features[i] * i_rms;')
out.append('        }')
out.append('')
out.append('        float * buf1 = buffer;')
out.append('        float * buf2 = buffer + 288;')
out.append('        input_layer1(features, buf1);')
out.append('        input_layer2(buf1, buf2);')
out.append('        int16_t * layer3_out = reinterpret_cast<int16_t *>(buf1);')
out.append('        input_layer3(buf2, layer3_out);')
out.append('')
out.append('        int32_t * temp1 = reinterpret_cast<int32_t *>(buffer);')
out.append('        int32_t * temp2 = temp1 + 288;')
out.append('        mingru<80>(layer3_out, rnn_state, RNN1_WEIGHT(), temp2);')
out.append('        mingru<64>(rnn_state, rnn_state + 64, RNN2_WEIGHT(), temp1);')
out.append('')
out.append('        return output_layer(rnn_state);')
out.append('    }')
out.append('};')
out.append('')
out.append('VoiceActivityDetector::VoiceActivityDetector(float threshold, uint32_t prefill_ms, uint32_t hangover_ms)')
out.append('    : impl_(new Impl()),')
out.append('      threshold_(threshold),')
out.append('      enter_threshold_(threshold),')
out.append('      exit_threshold_(std::max(0.05f, threshold * 0.70f)),')
out.append('      hangover_frames_(std::max(1u, hangover_ms / 16u)) {}')
out.append('')
out.append('VoiceActivityDetector::~VoiceActivityDetector() {')
out.append('    delete impl_;')
out.append('}')
out.append('')
out.append('VoiceActivityDetector::VoiceActivityDetector(VoiceActivityDetector && other) noexcept')
out.append('    : impl_(other.impl_),')
out.append('      threshold_(other.threshold_),')
out.append('      enter_threshold_(other.enter_threshold_),')
out.append('      exit_threshold_(other.exit_threshold_),')
out.append('      in_speech_(other.in_speech_),')
out.append('      accumulated_speech_ms_(other.accumulated_speech_ms_),')
out.append('      last_score_(other.last_score_),')
out.append('      last_level_dbfs_(other.last_level_dbfs_),')
out.append('      hangover_frames_(other.hangover_frames_),')
out.append('      hangover_rem_(other.hangover_rem_) {')
out.append('    other.impl_ = nullptr;')
out.append('}')
out.append('')
out.append('VoiceActivityDetector & VoiceActivityDetector::operator=(VoiceActivityDetector && other) noexcept {')
out.append('    if (this != &other) {')
out.append('        delete impl_;')
out.append('        impl_ = other.impl_;')
out.append('        threshold_ = other.threshold_;')
out.append('        enter_threshold_ = other.enter_threshold_;')
out.append('        exit_threshold_ = other.exit_threshold_;')
out.append('        in_speech_ = other.in_speech_;')
out.append('        accumulated_speech_ms_ = other.accumulated_speech_ms_;')
out.append('        last_score_ = other.last_score_;')
out.append('        last_level_dbfs_ = other.last_level_dbfs_;')
out.append('        hangover_frames_ = other.hangover_frames_;')
out.append('        hangover_rem_ = other.hangover_rem_;')
out.append('        other.impl_ = nullptr;')
out.append('    }')
out.append('    return *this;')
out.append('}')
out.append('')
out.append('float VoiceActivityDetector::predict_f32(FrameSpan frame) noexcept {')
out.append('    if (!impl_) {')
out.append('        return 0.0f;')
out.append('    }')
out.append('    // Branchless clamp [-1.0, 1.0]')
out.append('    alignas(32) float clamped[FRAME_SAMPLES];')
out.append('    for (size_t i = 0; i < FRAME_SAMPLES; ++i) {')
out.append('        clamped[i] = std::clamp(frame[i], -1.0f, 1.0f);')
out.append('    }')
out.append('    return impl_->predict_f32(std::span<const float, 256>(clamped));')
out.append('}')
out.append('')
out.append('std::expected<bool, VadError> VoiceActivityDetector::process_frame(FrameSpan frame, float * out_score) noexcept {')
out.append('    if (!impl_) {')
out.append('        return std::unexpected(VadError::Uninitialized);')
out.append('    }')
out.append('    for (size_t i = 0; i < FRAME_SAMPLES; ++i) {')
out.append('        if (!std::isfinite(frame[i])) {')
out.append('            return std::unexpected(VadError::InvalidInput);')
out.append('        }')
out.append('    }')
out.append('')
out.append('    // Compute RMS dBFS')
out.append('    double sum_sq = 0.0;')
out.append('    for (size_t i = 0; i < FRAME_SAMPLES; ++i) {')
out.append('        sum_sq += static_cast<double>(frame[i]) * static_cast<double>(frame[i]);')
out.append('    }')
out.append('    double mean_sq = sum_sq / 256.0;')
out.append('    last_level_dbfs_ = (mean_sq > 1e-12) ? static_cast<float>(10.0 * std::log10(mean_sq)) : -120.0f;')
out.append('')
out.append('    float score = 0.0f;')
out.append('    // Sub-microsecond energy pre-gate: skip neural net if silence (< -45 dBFS) and not in speech')
out.append('    if (!in_speech_ && last_level_dbfs_ < -45.0f) {')
out.append('        score = 0.0f;')
out.append('    } else {')
out.append('        score = predict_f32(frame);')
out.append('    }')
out.append('    last_score_ = score;')
out.append('    if (out_score) {')
out.append('        *out_score = score;')
out.append('    }')
out.append('')
out.append('    // Dual-threshold hysteresis gate')
out.append('    if (!in_speech_) {')
out.append('        if (score >= enter_threshold_) {')
out.append('            in_speech_ = true;')
out.append('            hangover_rem_ = hangover_frames_;')
out.append('            accumulated_speech_ms_ += 16;')
out.append('        }')
out.append('    } else {')
out.append('        if (score >= exit_threshold_) {')
out.append('            hangover_rem_ = hangover_frames_;')
out.append('            accumulated_speech_ms_ += 16;')
out.append('        } else if (hangover_rem_ > 0) {')
out.append('            --hangover_rem_;')
out.append('            accumulated_speech_ms_ += 16;')
out.append('        } else {')
out.append('            in_speech_ = false;')
out.append('        }')
out.append('    }')
out.append('    return in_speech_;')
out.append('}')
out.append('')
out.append('void VoiceActivityDetector::reset() noexcept {')
out.append('    if (impl_) {')
out.append('        impl_->reset();')
out.append('    }')
out.append('    in_speech_ = false;')
out.append('    accumulated_speech_ms_ = 0;')
out.append('    last_score_ = 0.0f;')
out.append('    last_level_dbfs_ = -100.0f;')
out.append('    hangover_rem_ = 0;')
out.append('}')
out.append('')
out.append('void VoiceActivityDetector::set_threshold(float threshold) noexcept {')
out.append('    threshold_ = std::clamp(threshold, 0.05f, 0.95f);')
out.append('    enter_threshold_ = threshold_;')
out.append('    exit_threshold_ = std::max(0.05f, threshold_ * 0.70f);')
out.append('}')
out.append('')
out.append('} // namespace transcribe')
out.append('')
out.append('// ---------------------------------------------------------------------------')
out.append('// Public C ABI Export Functions')
out.append('// ---------------------------------------------------------------------------')
out.append('extern "C" {')
out.append('')
out.append('struct transcribe_vad * transcribe_vad_init(float threshold) {')
out.append('    try {')
out.append('        return new transcribe_vad(threshold);')
out.append('    } catch (...) {')
out.append('        return nullptr;')
out.append('    }')
out.append('}')
out.append('')
out.append('void transcribe_vad_free(struct transcribe_vad * vad) {')
out.append('    delete vad;')
out.append('}')
out.append('')
out.append('float transcribe_vad_predict_frame(struct transcribe_vad * vad, const float * frame_256) {')
out.append('    if (!vad || !frame_256) {')
out.append('        return 0.0f;')
out.append('    }')
out.append('    return vad->detector.predict_f32(std::span<const float, 256>(frame_256, 256));')
out.append('}')
out.append('')
out.append('bool transcribe_vad_process_frame(struct transcribe_vad * vad, const float * frame_256, float * out_score) {')
out.append('    if (!vad || !frame_256) {')
out.append('        if (out_score) *out_score = 0.0f;')
out.append('        return false;')
out.append('    }')
out.append('    auto res = vad->detector.process_frame(std::span<const float, 256>(frame_256, 256), out_score);')
out.append('    return res.value_or(false);')
out.append('}')
out.append('')
out.append('void transcribe_vad_set_threshold(struct transcribe_vad * vad, float threshold) {')
out.append('    if (vad) {')
out.append('        vad->detector.set_threshold(threshold);')
out.append('    }')
out.append('}')
out.append('')
out.append('void transcribe_vad_reset(struct transcribe_vad * vad) {')
out.append('    if (vad) {')
out.append('        vad->detector.reset();')
out.append('    }')
out.append('}')
out.append('')
out.append('transcribe_status transcribe_stream_set_vad_threshold(struct transcribe_session * session, float threshold) {')
out.append('    if (!session) {')
out.append('        return TRANSCRIBE_ERR_INVALID_ARG;')
out.append('    }')
out.append('    if (threshold < 0.05f || threshold > 0.95f) {')
out.append('        return TRANSCRIBE_ERR_INVALID_ARG;')
out.append('    }')
out.append('    session->stream_vad.set_threshold(threshold);')
out.append('    return TRANSCRIBE_OK;')
out.append('}')
out.append('')
out.append('}')
out.append('')

content = '\n'.join(out)
with open(r"C:\Users\Z\Downloads\PROJECTS\transcribe-fork\src\transcribe-vad.cpp", "w", encoding="utf-8") as f:
    f.write(content)
print(f"Generated transcribe-vad.cpp successfully, {len(content)} characters.")
